import { InstanceApi } from "@sdk/cmdb-sdk";

export const mockFetchCmdbInstanceDetailReturnValue: Partial<InstanceApi.GetDetailResponseBody> = {
  NumberTen: [],
  SWITCH: [],
  SWITCH1: [],
  _SERVICENODE: [],
  _agentHeartBeat: -1,
  _agentStatus: "未安装",
  _deviceList_CLUSTER: [],
  _host__IDCRACK: [],
  _host__ROUTER: [],
  _host__SWITCH: [],
  _object_id: "HOST",
  _object_version: 0,
  _order_ip: 0,
  _ts: 1551491154,
  _version: 1,
  backupowner: [
    {
      _is_auto_discovery: null,
      _object_id: "USER",
      _object_version: 0,
      _ts: 1553505937,
      _version: 1,
      creator: "easyops",
      ctime: "2019-03-25 17:25:37",
      instanceId: "584e7c99063a4",
      name: "wimihe22",
      nickname: null,
      org: 8888,
      state: "valid",
      user_email: "wimihe22@easyops.cn",
      user_memo: null,
      user_tel: null,
      wework_userid: null
    },
    {
      _is_auto_discovery: null,
      _object_id: "USER",
      _object_version: 0,
      _ts: 1553479717,
      _version: 1,
      creator: "easyops",
      ctime: "2019-03-25 10:08:37",
      instanceId: "584e1aebe654b",
      name: "tester0009114",
      nickname: null,
      org: 8888,
      state: "valid",
      user_email: "tester0009114@easyops.cn",
      user_memo: null,
      user_tel: null,
      wework_userid: null
    }
  ],
  creator: "defaultUser",
  ctime: "2019-03-02 09:45:54",
  deviceId: "fc762344455470002ed3aa3ad2def8c2",
  hostname: "wimihetest23",
  instanceId: "58312af20a20d",
  ip: "0.0.0.0",
  org: 8888,
  tag: ["biaoqian", "\t和东方红", "合法化的,fhfh"],
  owner: [
    {
      _object_id: "USER",
      _object_version: 1,
      _pre_ts: 0,
      _ts: 1551317080,
      _version: 1,
      creator: "",
      ctime: "2019-02-28 09:24:40",
      instanceId: "5c77385848da1",
      modifier: "",
      mtime: "",
      name: "test",
      nickname: "",
      org: 8888,
      state: "valid",
      user_email: "test@qq.com",
      user_memo: "",
      user_tel: "",
      wework_userid: ""
    },
    {
      _is_auto_discovery: null,
      _object_id: "USER",
      _object_version: 0,
      _ts: 1553508972,
      _version: 1,
      creator: "defaultUser",
      ctime: "2019-03-25 18:16:12",
      instanceId: "584e87e6ea1a1",
      name: "wimihe22",
      nickname: null,
      org: 8888,
      state: "valid",
      user_email: "wimihe22@easyops.cn",
      user_memo: null,
      user_tel: null,
      wework_userid: null
    }
  ],
  status: "运营中",
  wimitest: []
};
