name: Yarn renew

on: workflow_dispatch

jobs:
  renew:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN_EVE }}
        fetch-depth: 0

    - run: |
        git config --global user.name 'easyops-eve'
        git config --global user.email 'easyops-eve@users.noreply.github.com'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - uses: easyops-cn/actions-next-manually-renew@master

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_TOKEN_EVE }}
        branch: easyops-eve/renew
        title: Yarn renew
        author: easyops-eve <easyops-eve@users.noreply.github.com>
        committer: easyops-eve <easyops-eve@users.noreply.github.com>
        commit-message: 'chore(): yarn renew'
        body: Manually yarn renew by Github Actions.
